apiVersion: v1
kind: List
items:
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: s2i-angular
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 's2i-angular:1.0'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/gildasio719/s2i-angular-nginx.git'
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    triggers: []
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: s2i-angular
      version: "v1"
    name: s2i-angular
  spec:
    tags:
      - name: latest
        annotations:
          description: "Build Angular apps with CLI and run them with NGINX"
          iconClass: "js-icon"
          supports: "angular,angular:1"
          tags: "builder,nginx"
          version: "1"
        from:
          kind: "ImageStreamTag"
          name: "latest"
